#' Convert eCH-0159 XML file into a dataframe
#'
#'`parse_eCH_0159()` turns an eCH-0159 XML file for a vote day into a dataframe.
#' Currently, the function supports input files for votes generated by the application VOTING.
#'
#' @param file Path to your XML file.
#'
#' @return A dataframe.
#' @export
#'
#' @examples
#' \dontrun{
#' filepath <- system.file("extdata", "eCH-0159_abraxas_votes_ZH_majority_2026-06-16.xml")
#' votedata <- parse_eCH_0159(filepath)
#' }
parse_eCH_0159 <- function(file){

  browser()

  # Load file and strip namespaces
  xml_data <- xml2::read_xml(file)

  # Strip namespaces
  xml_data_stripped <- strip_namespaces(xml_data)

  # Load initial delivery part of the file
  node_initialDelivery <- xml2::xml_find_first(xml_data_stripped, ".//initialDelivery")


  # SPECIFY SPECIAL NODES' NAMES ===============================================


  # Nodes containing language nodes
  specify_node(node_initialDelivery, "language")

  # Nodes containing language nodes (that are called "Key" here)
  specify_node(node_initialDelivery, "Key")


  # TURN TO DF =================================================================


  ## Contest Information -------------------------------------------------------


  # Get structure of the indexed node as a list
  initialDelivery_list <- node_initialDelivery |>
    xml2::as_list()

  # Number the names to create a unique name for each child
  names(initialDelivery_list) <- paste0(1:length(initialDelivery_list),"_", names(initialDelivery_list))

  # Define contest node and electionGroupBallot nodes as named lists
  contest_list <- initialDelivery_list[1]
  voteInformation_list <- initialDelivery_list[-1]

  # Unlist the list
  contest_unlist <- unlist(contest_list)

  # List to df and add unique id (if )
  contest_df_long <- to_df(contest_unlist, names(contest_unlist)) |>
    dplyr::mutate(unique_id = gsub("^(\\d+)_.*", "\\1", var))

  # Write contest information to a df (and add a join_id)
  contest_df <- contest_df_long |>
    to_wide() |>
    dplyr::select(-unique_id) |>
    tidyr::unnest_longer(tidyselect::everything()) |>
    dplyr::mutate(join_id = 1879)


   ## Vote Information ---------------------------------------------------------


  # Define all voteInformation nodes.
  # This is needed to work with further down the tree.
  # For the next level, we already defined a named list above.
  voteInformation_nodes <- xml2::xml_find_all(node_initialDelivery, ".//voteInformation")

  # Parse through all voteInformation nodes
  vote_list <- lapply(seq_along(voteInformation_nodes), function(voteInformation_index){

    # Define node of interest
    voteInfo <- voteInformation_nodes[[voteInformation_index]]


    #### Vote ------------------------------------------------------------------


    vote <- xml2::xml_find_first(voteInfo, ".//vote")

    # Get structure of the indexed node as a list
    vote_list <- vote |>
      xml2::as_list()

    # Add node's name (so that we are always have two levels in var_short downstream)
    names(vote_list) <- paste0(xml2::xml_name(vote),"_", names(vote_list))

    # Unlist the list
    vote_unlist <- unlist(vote_list)

    # List to df and add unique id
    vote_df_long <- to_df(vote_unlist, names(vote_unlist))

    # Define vote information
    vote_df <- vote_df_long |>
      to_wide() |>
      tidyr::unnest_longer(
        tidyselect::everything(),
        keep_empty = TRUE
      ) |>
      dplyr::mutate(join_id = 1879)


    #### Ballots ---------------------------------------------------------------


    # Define all ballot nodes (as one nodeset)
    ballot_nodes <- xml2::xml_find_all(voteInfo, ".//ballot")

    # Parse through all ballot nodes
    ballot_list <- lapply(seq_along(ballot_nodes), function(ballot_index){

      # Define node of interest
      ballot <- ballot_nodes[[ballot_index]]

      # Get structure of the indexed node as a list
      ballot_list <- ballot |>
        xml2::as_list()


      # STAND HIER ====


      # Number the names to create unique names
      names(ballot_list) <- paste0(1:length(ballot_list),"_", names(ballot_list))

      # Unlist the list
      voteInfo_unlist <- unlist(voteInfo_list)

      # List to df and add unique id
      voteInfo_df_long <- to_df(voteInfo_unlist, names(voteInfo_unlist)) |>
        dplyr::mutate(unique_id = gsub("^(\\d+)_.*", "\\1", var))


    #### Vote ------------------------------------------------------------------


    # Define vote information
    vote_df <- voteInfo_df_long |>
      dplyr::filter(grepl("vote\\.", var)) |>
      to_wide() |>
      dplyr::select(-unique_id) |>
      tidyr::unnest_longer(
        tidyselect::everything(),
        keep_empty = TRUE
      ) |>
      dplyr::mutate(join_id = 1879)


    #### Ballots ---------------------------------------------------------------


    # Define candidate information
    ballot_df <- voteInfo_df_long |>
      dplyr::filter(grepl("ballot\\.", var)) |>
      to_wide() |>
      dplyr::select(-unique_id) |>
      tidyr::unnest_longer(
        tidyselect::everything(),
        keep_empty = TRUE
      ) |>
      dplyr::mutate(join_id = 1879)


    #### Join ----------------------------------------------------------------


    voteInfo_df <- vote_df |>
      dplyr::left_join(ballot_df, by = "join_id")










    ### Parse Vote Information -------------------------------------------------


    voteInformation <- voteInformation_list[voteInformation_index]

    # Define nodes of interest as named list
    vote_list <- list(voteInformation[[1]][names(voteInformation[[1]]) != "ballot"])
    names(vote_list) <- names(voteInformation)

    # Unlist
    vote_unlist <- unlist(vote_list)

    # To df and add unique ID
    vote_df_long <- to_df(vote_unlist, names(vote_unlist)) |>
      dplyr::mutate(unique_id = gsub("^(\\d+)_.*", "\\1", var))

    # Write vote information to a df and add ID for join
    vote_df <- vote_df_long |>
      to_wide() |>
      dplyr::select(-unique_id) |>
      tidyr::unnest_longer(
        tidyselect::everything(),
        keep_empty = TRUE
      ) |>
      dplyr::mutate(join_id = 1879)


    ### Parse Ballot Information -----------------------------------------------


    # Define all ballot information nodes
    ballot_nodes <- xml2::xml_find_all(voteInformation_nodes[voteInformation_index], ".//ballot")

    # Parse through all ballot nodes
    ballot_list <- lapply(seq_along(ballot_nodes), function(ballot_index) {

      # Define node of interest
      ballot <- ballot_nodes[[ballot_index]]

      # Get structure of the indexed node as a list
      ballot_ls <- ballot |>
        xml2::as_list()

      browser()

      # # Number the names to create unique names --> not needed here, the content of the ballot node is unique already
      # names(ballot_ls) <- paste0(1:length(ballot_ls),"_", names(ballot_ls))

      # Unlist the list
      ballot_unls <- unlist(ballot_ls)

      # List to df and add unique id
      ballot_df_long <- to_df(ballot_unls, names(ballot_unls)) #|>
        # dplyr::mutate(unique_id = gsub("^(\\d+)_.*", "\\1", var))

      # Write vote information to a df and add ID for join
      ballot_df <- ballot_df_long |>
        to_wide() |>
        # dplyr::select(-unique_id) |>
        tidyr::unnest_longer(
          tidyselect::everything(),
          keep_empty = TRUE
        ) |>
        dplyr::mutate(join_id = 1879)

    })

    # Bind rows to df
    ballots_df <-  dplyr::bind_rows(ballot_list)

  })




  # STAND HIER ===================





  })












  # Bind the tables in the electionGroup_list
  electionGroup_df <- dplyr::bind_rows(electionGroup_list)

  # Join contest information and electionGroup data and remove the join_id
  contest_data_complete <- contest_df |>
    dplyr::left_join(electionGroup_df) |>
    dplyr::select(-join_id)

  return(contest_data_complete)

}

