#' Convert eCH-0157 XML file into a dataframe
#'
#'`parse_eCH_0157()` turns an eCH-0157 XML file for an election day into a dataframe.
#' Currently, the function supports input files for votes generated by the application VOTING.
#'
#' @param file Path to your XML file.
#'
#' @return A dataframe.
#' @export
#'
#' @examples
#' \dontrun{
#' filepath <- system.file("extdata", "eCH-0157_abraxas_elections_ZH_majority_2026-06-16.xml")
#' votedata <- parse_eCH_0157(filepath)
#' }
parse_eCH_0157 <- function(file){

  # Load file and strip namespaces
  xml_data <- xml2::read_xml(file)

  # Strip namespaces
  xml_data_stripped <- strip_namespaces(xml_data)

  # Load initial delivery part of the file
  node_initialDelivery <- xml2::xml_find_first(xml_data_stripped, ".//initialDelivery")


  # CONTEST INFORMATION ========================================================


  # Define contest node
  contest_node <- xml2::xml_find_first(node_initialDelivery, ".//contest")

  # Parse contest node and add join id
  contest_df <- parse_node(contest_node) |>
    dplyr::mutate(join_id = 1879)


  # ELECTION INFORMATION =======================================================


  # Define election groups
  electionGroup_nodes <- xml2::xml_find_all(node_initialDelivery, ".//electionGroupBallot")

  # Parse all electionGroupBallot nodes
  electionGroup_list <- lapply(seq_along(electionGroup_nodes), function(electionGroup_index) {

    # Define DOI of election group
    domainOfInfluenceIdentification <- xml2::xml_text(xml2::xml_find_first(electionGroup_nodes[electionGroup_index], ".//domainOfInfluenceIdentification"))

    # List all elections in the current election group
    electionInformation_nodes <- xml2::xml_find_all(electionGroup_nodes[electionGroup_index], ".//electionInformation")

    # Parse every election and create a list
    electionInformation_list <- lapply(seq_along(electionInformation_nodes), function(electionInformation_index){

      # Define election and candidate elements
      election_node <- xml2::xml_find_all(electionInformation_nodes[electionInformation_index], ".//election") # There can only be one election node on this level
      candidate_nodes <- xml2::xml_find_all(electionInformation_nodes[electionInformation_index], ".//candidate")

      # Stop if there are more than one election
      if (length(election_node) > 1) {
        stop(paste0(
          "There seem to be more than one election node in the electionInformation node for DOI ",
          xml2::xml_text(xml2::xml_find_first(electionInformation_nodes[electionInformation_index], ".//domainOfInfluenceIdentification"))
        ))
      }

      ## Parse Election Element ------------------------------------------------


      election_df <- parse_node(election_node)


      ## Parse Candidate Elements ----------------------------------------------


      candidate_list <- lapply(seq_along(candidate_nodes), function(candidate_index){
        parse_node(candidate_nodes[candidate_index])
      })

      # Turn list to df by binding rows
      candidate_df <- dplyr::bind_rows(candidate_list)


      ## Join Election and Candidate Information -------------------------------


      # Add id columns
      election_df <- election_df |>
        dplyr::mutate(join_id = 1879)
      candidate_df <- candidate_df |>
        dplyr::mutate(join_id = 1879)

      # Join
      election_df <- election_df |>
        dplyr::right_join(candidate_df, by = "join_id")

    })

    # Bind all elections and add DOI
    elections_df <- dplyr::bind_rows(electionInformation_list) |>
      dplyr::mutate(domainOfInfluenceIdentification = domainOfInfluenceIdentification)

  })

  elections_groups_df <- dplyr::bind_rows(electionGroup_list)


  # JOIN CONTEST AND ELECTION INFO ===========================================


  # Join
  all_elections_df <- contest_df |>
    dplyr::right_join(elections_groups_df, by = "join_id") |>
    dplyr::select(-join_id)

}
