#' Convert eCH-0157 XML file into a dataframe
#'
#'`parse_eCH_0157()` turns an eCH-0157 XML file for a vote into a dataframe.
#' Currently, the function supports input files for votes generated by the
#' applications VOTING and VeWork.
#'
#' @param file Path to your XML file.
#'
#' @return A dataframe.
#' @export
#'
#' @examples
#' \dontrun{
#' filepath <- system.file() # fill in
#' votedata <- parse_eCH_0157(filepath)
#' }
parse_eCH_0157 <- function(file){

  # Load file
  xml_data <- xml2::read_xml(file)

  # Define namespaces
  namespaces <- xml2::xml_ns(xml_data)

  # Define the prefixes we need (depends on exact file structure)
  ns0010 <- names(namespaces[grep("0010", namespaces)])[1]
  ns0058 <- names(namespaces[grep("0058", namespaces)])[1]
  ns0155 <- names(namespaces[grep("0155", namespaces)])[1]
  ns0157 <- names(namespaces[grep("0157", namespaces)])[1]

  # Load initial delivery part of the file
  node_initialDelivery <- xml2::xml_find_first(xml_data, paste0(".//", ns0157, ":initialDelivery"))


  # CONTEST INFORMATION ========================================================


  # Define constest id
  contestIdentification <- xml2::xml_find_first(node_initialDelivery, paste0(".//", ns0155, ":contestIdentification")) |>
    xml2::xml_text()

  # Define polling day
  contestDate <- xml2::xml_find_first(node_initialDelivery, paste0(".//", ns0155, ":contestDate")) |>
    xml2::xml_text()

  # Define contest description
  contestDescription <- read_contestDescription(node_initialDelivery)

  # Join all contest information
  contest <- data.frame(
    contestIdentification,
    contestDate,
    contestDescription
  )


  # ELECTION INFORMATION =======================================================


  electionGroup_name <- xml2::xml_name(xml2::xml_find_all(node_initialDelivery, paste(".//", ns0157, ":electionGroupBallot")))

  # Define index of electionGroupBallot nodes
  relevant <- which(grepl(electionGroup_name, node_initialDelivery)) + 1

  # Stop if there are no relevant nodes
  if (length(relevant) == 0) {
    stop("There are no elections in your data.")
  }

  # Apply read_electionGroupBallot function to all relevant children
  out_list <- lapply(relevant, function(x) {

    read_electionGroupBallot(
      xml2::xml_children(node_initialDelivery)[x] # STAND HIER: Funktion unten fertig schreiben mit der utils function =================================================
    )

  })









  # Define domain of influence types found in data
  domainofOnfluenceType <- xml2::xml_find_all(node_voteBaseDelivery, paste0(".//", ns0252, ":domainOfInfluence")) |>
    xml2::xml_find_all(paste0(".//", ns0155, ":domainOfInfluenceType")) |>
    xml2::xml_text()

  # Define index of votes with the relevant domain of influence types (must be +2 since the first two nodes are not of interest)
  relevant <- which(grepl(paste0(doi, collapse = "|"), domainofOnfluenceType)) + 2








}







#' Read eCH-0157 election information element
#'
#' @param xml_node Node XXXXXXXXXXXXXXXXX of the XML file.
#'
#' @return A dataframe.
#' @export
#'
#' @examples
#' \dontrun{
#'
#' }
read_electionGroupBallot <- function(xml_node = node_initialDelivery) {

  # Define domain of influence id
  domainOfInfluenceIdentification <- xml2::xml_find_first(xml_node, paste0(".//", ns0157, ":domainOfInfluenceIdentification")) |>
    xml2::xml_text()

  # Define election information node
  node_electionInformation <- xml2::xml_find_first(xml_node, paste0(".//", ns0157, ":electionInformation"))

  read_language_text_node(xml2::xml_children(node_electionInformation)[1])







  # # Define election
  # node_election <- xml2::xml_find_first(xml_data, paste0(".//", ns0157, ":election"))
  # eigentlich eher alle children definieren und dann darüber applyen
  # Define children



  # STAND HIER --> DA KOMMT JETZT DIE LANGUAGE TEXT NODE FUNKTION MIT EINEM LAPPLY REIN





}





#' Read eCH-0157 contest description element
#'
#' @param xml_node Node voteBaseDelivery of the XML file.
#'
#' @return A dataframe.
#' @export
#'
#' @examples
#' \dontrun{
#'
#' }
read_contestDescription <- function(xml_node = node_initialDelivery) {

  # Load contest description node
  node_contestDescription <- xml2::xml_find_first(xml_node, paste0(".//", ns0155, ":contestDescription"))

  # Extract all "subtotalInfo" nodes
  contestDescriptionInfo_nodes <- xml2::xml_find_all(node_contestDescription, paste0(".//", ns0155, ":contestDescriptionInfo"))

  # Extract all children of the node
  children <- xml2::xml_children(contestDescriptionInfo_nodes)

  # Create a named list with element names as keys and their text as values
  data <- stats::setNames(xml2::xml_text(children), xml2::xml_name(children))

  # Turn into data frame
  data_tbl <- data.frame(
      language = data[names(data) == "language"],
      contestDescription = data[names(data) == "contestDescription"]
  )

  # Define new variable names in a new column, then widen data
  data_tbl <- data_tbl |>
    dplyr::rowwise() |>
    dplyr::mutate(
      new_var = paste(names(data_tbl)[2], dplyr::pull(dplyr::pick(1)), sep = "_")
    ) |>
    dplyr::ungroup() |>
    dplyr::select(-1) |>
    tidyr::pivot_wider(
      names_from = new_var,
      values_from = 1
    )

  return(data_tbl)

}



