#' Strip namespaces.
#'
#' @description
#' This function strips all namespaces of eCH-0157 and eCH-0252 XML files.
#' It works for files generated by VOTING and VeWork.
#'
#' @param xml_data A list of class xml_document.
#'
#' @return A list of class xml_document.
#' @export
#'
#' @examples
#' \dontrun{
#' filepath <- system.file(
#'   "extdata",
#'   "eCH-0252_abraxas_vote_ZH_counting_2024-11-24.xml",
#'   package = "eCHparser"
#' )
#'
#' # Load file
#' xml_data <- xml2::read_xml(filepath)
#'
#' # Strip namespaces
#' xml_data_stripped <- strip_namespaces(xml_data)
#' }
strip_namespaces <- function(xml_data) {

  # If we find the node deliveryHeader without prefix, remove all namespaces with xml_ns_strip()
  if(grepl("<deliveryHeader>", as.character(xml_data))) {

    xml_data_stripped <- xml2::xml_ns_strip(xml_data)

  # Otherwise, handle the entire file as string and remove them using gsub().
  } else {

    xml_data_stripped <- xml2::as_xml_document(gsub("eCH-\\d{4}:", "", as.character(xml_data)))

  }

  return(xml_data_stripped)

}





#' Amend node parents' names with node specification
#'
#' @description
#' Certain nodes have a different logic, insofar as they do not themselves specify their content in the name but do this in one of the children.
#' Examples of this are the namedElement or the otherIdentification nodes, or also nodes, that contain multilingual content.
#' To create unique names that define their content, we specify their parents' names.
#'
#' @param node An xml node.
#' @param spec_element The name of the specification element that contains text.
#'
#' @return An xml node.
specify_node <- function(node, spec_element) {

  # Define search tag
  search_tag <- paste0(".//", spec_element)

  # Define all specification nodes
  spec_nodes <- xml2::xml_find_all(node, search_tag)

  # Get all specifications
  specs <- spec_nodes |>
    xml2::xml_text()

  # Define parent nodes
  parent_nodes <- xml2::xml_parent(spec_nodes)

  # Get all parents' original names
  parents_names <- xml2::xml_name(parent_nodes)

  # Combine original names with specification to create unique names and rename nodes
  xml2::xml_name(parent_nodes) <- paste(parents_names, specs, sep = "-")

  # Remove specification nodes
  xml2::xml_remove(spec_nodes)

}





#' Amend voter information subtotalInfo nodes with node specifications
#'
#' @description
#' Trial of alternative to the unpack_voters() helper function.
#'
#' @param node An xml node.
#'
#' @return An xml node.
specify_voter_node <- function(node) {


  # AMEND WITH VOTER TYPE ======================================================


  # Define all voterType nodes
  voterType_nodes <- xml2::xml_find_all(node, ".//voterType")

  # Get all voterTypes
  voterTypes <- voterType_nodes |>
    xml2::xml_text()

  # Define parent nodes
  parent_nodes <- xml2::xml_parent(voterType_nodes)

  # Get all parents' original names
  parents_names <- xml2::xml_name(parent_nodes)

  # Combine original names with specification to create unique names and rename nodes
  xml2::xml_name(parent_nodes) <- paste0(parents_names, "-voterType", voterTypes)

  # Remove specification nodes
  xml2::xml_remove(voterType_nodes)


  # AMEND WITH SEX =============================================================


  # Define all sex nodes
  sex_nodes <- xml2::xml_find_all(node, ".//sex")

  # Get all sexes
  sexes <- sex_nodes |>
    xml2::xml_text()

  # Define parent nodes
  parent_nodes <- xml2::xml_parent(sex_nodes)

  # Get all parents' original names
  parents_names <- xml2::xml_name(parent_nodes)

  # Combine original names with specification to create unique names and rename nodes
  xml2::xml_name(parent_nodes) <- paste0(parents_names, "-sex", sexes)

  # Remove specification nodes
  xml2::xml_remove(sex_nodes)

}





#' Convert long dataframe to wide
#'
#' @param data A long dataframe.
#'
#' @return A dataframe.
to_wide <- function(data){

  if ("var" %in% names(data)){
    data <- data |>
      # Delete var to make the pivot work
      dplyr::select(-var)
  }

  data |>
    tidyr::pivot_wider(
      names_from = var_short,
      values_from = data,
      values_fn = list
    )

}





#' Unlist list to dataframe
#'
#' @param data A dataframe.
#' @param names A string of variable names.
#'
#' @return A dataframe.
to_df <- function(data, names){

  data.frame(
    data = data,
    var = names
  ) |>
    dplyr::mutate(
      # Keep only string after second to last "."
      var_short = gsub("^.*?\\.([^.]+\\.[^.]+)$", "\\1", var),
      # Remove digits followed by an underscore at the start of the string
      var_short = gsub("^\\d+_", "", var_short),
      # Replace "." with "_"
      var_short = gsub("\\.", "_", var_short)
    )

}





#' Extract all attributes from a list
#'
#' @param my_list A list.
#' @param path A character vector of length 1.
#' @param results A list.
#'
#' @return A list.
extract_attributes <- function(my_list, path = character(), results = list()){

  if (is.list(my_list)) {

    for (i in seq_along(my_list)) {

      element <- my_list[[i]]
      name <- names(my_list)[i]

      # Get namespace if available
      ns <- attr(element, "xmlns")

      # Construct full path for clarity (optional)
      full_path <- c(path, name)

      # Save result
      results[[length(results) + 1]] <- list(
        path = paste(full_path, collapse = "/"),
        name = name,
        namespace = ns
      )

      # Recurse if the element is also a list
      if (is.list(element)) {
        results <- extract_attributes(element, path = full_path, results = results)
      }
    }

  }

  # Drop duplicates
  results <- unique(results)

  return(results)

}





#' Assign attributes by their name/path
#'
#' @param my_list A list.
#' @param ns_info A list of name-namespace pairs.
#'
#' @return A list.
assign_namespaces_by_name <- function(x, ns_info) {

  for (i in seq_along(x)) {

    name <- names(x)[i]
    elem <- x[[i]]

    # Safely extract matching namespace
    match_idx <- which(vapply(ns_info, function(info) {
      is.list(info) && !is.null(info$name) && info$name == name
    }, logical(1)))

    if (length(match_idx) > 0) {
      ns <- ns_info[[match_idx[1]]]$namespace
      attr(elem, "xmlns") <- ns
    }

    # Recurse if the element is a list
    if (is.list(elem)) {
      elem <- assign_namespaces_by_name(elem, ns_info)
    }

    x[[i]] <- elem

  }

  return(x)

}
